name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 19 * * 6'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: 'requirements.txt'
    - name: Fetch latest data
      run: python harvest_recently_digitised.py
    - name: Commit and push if it changed
      run: |-
        git config user.name 'Automated'
        git config user.email 'actions@users.noreply.github.com'
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
